[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[plugins.inputs]
	custom_build_dir_name = "out_publish"
